name: ci

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main
  
jobs:
  ci:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install dependencies
        run: npm ci
      # - name: Check formatting
      #   run: pnpm run format:check
      - name: Lint
        run: npm run lint
      # - name: Run verify types
      #   run: pnpm run verify-types
      - name: Build project
        run: |
          touch .env.local
          echo CONVEX_DEPLOYMENT=${{ secrets.CONVEX_DEPLOYMENT }} >> .env.local
          echo NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }} >> .env.local
          npm run build
      # - name: Run test with coverage
      #   run: pnpm run coverage